### PR TITLE
Add API document

### PR DESCRIPTION
**Pull request by kbumsik**
This PR is for API and web page URL document.

I will merge it when the document is pretty much completed.

### CODE REVIEW

**Comment by cjackie** [comment]
Could you also provide a API for getting information about the user?

**Comment by kbumsik** [comment]
Do you mean something `/api/getUserInfo` in #6  ?
I think using `GET /api/location` and `GET /api/device` will get what you want.
We don't need to make single query that does many things.

**Comment by cjackie** [comment]
no, i meant info about user such as username, last login time and so on.

``` javascript
{
    'username': 'jack',
    'created time': '...'
}
```

Anyway, this API is not that important.

**Comment by kbumsik** [comment]
Opps, I thought you could assess username by accessing session variable using JavaScript.
But I realized Flask encrypts the session variable so JavaScript can not access to it. 😛 

I will add `GET /api/current_user` to get `username` and `last_login` to return name and login time.

**Pull request merged**
