### PR TITLE
Fixed Web API for Devices

### PR DESCRIPTION
**Pull request by kbumsik**
One of #6 . ⚠️ In progress
I made change in `/api/device` related Web API. I separated Device and Parameters.
When you just need a list of device with latest data, you can call `GET /api/device` and `GET /api/device/<id>/parameter`, without getting detail using `GET /api/device/<id>`
Please tell me if there is anything needed to be changed.

### CODE REVIEW

**Comment by cjackie** [comment]
These api relating to device are easier for me to work with! That is nice. 

One question:

```
/api/location/<id>
get detail of location #id
```

What is data format of the detail.

**Comment by kbumsik** [comment]
Basically, the biggest reason why I separated APIs like `GET /api/location/` and `GET /api/location/<id>` is that you will have situation that you don't really need to get a full list of location.

I added description of API you requested. I added name of parent location and list of child rooms. 

I also added `GET /api/location/<id>/device`. It will get a list of devices that is located in that room.

**Comment by cjackie** [comment]
Don't forget to merge this if you are done, so that we lock down these APIs(stable api, and further changes to them should be backward compatible) 😄

**Comment by kbumsik** [comment]
Opps, I forget to merge 😛 . I will check if the design so far is future-proof and then merge.

**Comment by kbumsik** [comment]
It looks done right now. I merge it.

**Pull request merged**
